// ─── PDFExportModal ──────────────────────────────────────────────────────
//
// PR 29.1: Modal that lets the teacher pick PDF style + variant before
// downloading. Replaces the temporary localStorage hack from PR 29.0.2
// which required hand-editing localStorage to preview a non-default style.
//
// Layout (~640px wide modal):
//
//   ┌────────────────────────────────────────────────────────────────┐
//   │  Exportar PDF                                              [X] │
//   │  Elegí el estilo y el tipo                                     │
//   │                                                                │
//   │  Tipo:  [ Examen ]  [ Clave de respuestas ]                    │
//   │                                                                │
//   │  Estilo:                                                       │
//   │  ┌────────┐  ┌────────┐  ┌────────┐                            │
//   │  │ thumb  │  │ thumb  │  │ thumb  │                            │
//   │  │ classic│  │ modern │  │ editor │                            │
//   │  └────────┘  └────────┘  └────────┘                            │
//   │                                                                │
//   │  Vista previa:                                                 │
//   │  ┌────────────────────────────────────────────────────────────┐│
//   │  │                                                            ││
//   │  │              iframe with rendered PDF                       ││
//   │  │                                                            ││
//   │  └────────────────────────────────────────────────────────────┘│
//   │                                                                │
//   │                              [ Cancelar ]   [ Descargar PDF ] │
//   └────────────────────────────────────────────────────────────────┘
//
// Style choice is sticky via localStorage.clasloop_pdf_style — the next
// time the modal opens, the last chosen style is pre-selected.
//
// Preview is generated by calling exportPDF with a "preview" mode that
// returns the blob instead of triggering the browser download. The blob
// is wrapped in an object URL and shown in an iframe. Regenerated each
// time the style or variant changes.

import { useState, useEffect, useRef } from "react";
import jsPDF from "jspdf";
import { ensureKoreanFont } from "../lib/pdf-fonts";
import { PALETTES, getPalette, DEFAULT_PALETTE_ID } from "../lib/pdf-styles/palettes";
import * as classic from "../lib/pdf-styles/classic";
import * as modern from "../lib/pdf-styles/modern";
import * as editorial from "../lib/pdf-styles/editorial";
import * as framed from "../lib/pdf-styles/framed";
import { drawScanSheet } from "../lib/pdf-styles/scanner";
// PR 75: i18n centralizado
import { useT } from "../i18n";
import { useToast } from "../lib/toast";
// Landing PR B: the style thumbnails moved to their own dep-free module so the
// marketing landing can reuse the exact same SVGs without importing jsPDF.
import { STYLE_THUMBS } from "./PdfStyleThumbs";
import { SH } from "./tokens";
import Button from "./ui/Button";
import Modal from "./Modal";
import CleoTour from "../onboarding/CleoTour";

// PR 46: scanner ya no es un "estilo" — es una página opcional que se
// preempts al examen cuando variant === "exam_with_scan". El style
// picker no lo muestra.
const STYLES = { classic, modern, editorial, framed };

// Per-style default font, mirroring pdf-export.js. Framed uses Times.
const STYLE_FONT_DEFAULTS = {
  framed: "times",
};

const STORAGE_KEY = "clasloop_pdf_style";
const PALETTE_STORAGE_KEY = "clasloop_pdf_palette";
const DEFAULT_STYLE = "classic";
// PR 46: cuántos styles ver de una vez en el carrusel. 3 entra cómodo
// en el ancho del modal sin que cada uno quede muy chico.
const VISIBLE_STYLES = 3;

// i18n strings for the modal — kept local since this is the only place
// they're used. EN / ES / KO follow the same key set.
// PR 75: el bloque i18n local fue movido a src/i18n/{en,es,ko}.js
// bajo el namespace "pdfExportModal".

// ─── Thumbnail SVGs ──────────────────────────────────────────────────────
// Moved to ./PdfStyleThumbs (dep-free, shared with the marketing landing).
// Imported as STYLE_THUMBS at the top of this file.

// ─── Generate a preview blob (no download trigger) ────────────────────────
// Same logic as exportPDF but instead of calling doc.save(), we return
// the blob URL so the modal can show it in an iframe.
async function generatePreviewBlobURL(deck, classObj, { style, variant, lang, paletteId }) {
  const renderer = STYLES[style] || STYLES.classic;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  // PR 81: detectar hangul en el contenido del deck, no solo en deck.language.
  // Ver comentario equivalente en src/lib/pdf-export.js para detalles.
  const HANGUL_RE = /[\uAC00-\uD7A3]/;
  const hasKoreanContent = (() => {
    try {
      const stringified = JSON.stringify({
        title: deck.title,
        description: deck.description,
        questions: deck.questions,
      });
      return HANGUL_RE.test(stringified);
    } catch {
      return false;
    }
  })();
  const useKorean =
    (deck.language || "").toLowerCase() === "ko" || hasKoreanContent;
  if (useKorean) {
    await ensureKoreanFont(doc);
  }
  const fontFamily = useKorean
    ? "NotoSansKR"
    : (STYLE_FONT_DEFAULTS[style] || "helvetica");
  // PR 32: resolve palette by id
  const palette = getPalette(paletteId || DEFAULT_PALETTE_ID);
  const renderOpts = { lang, fontFamily, palette };
  if (variant === "answer_key") {
    await renderer.renderAnswerKey(doc, deck, classObj, renderOpts);
  } else if (variant === "exam_with_scan") {
    // PR 46: prepend la hoja escaneable, después el exam con el style elegido
    await drawScanSheet(doc, deck, classObj, {
      lang,
      fontFamily: useKorean ? "NotoSansKR" : "helvetica",
    });
    doc.addPage();
    await renderer.renderExam(doc, deck, classObj, renderOpts);
  } else {
    await renderer.renderExam(doc, deck, classObj, renderOpts);
  }
  const blob = doc.output("blob");
  return URL.createObjectURL(blob);
}

// ─── Component ───────────────────────────────────────────────────────────
export default function PDFExportModal({
  deck,
  classObj,
  lang = "en",
  initialVariant = "exam",
  onClose,
  // Theme tokens for consistency with the rest of the app
  C,
  // For the first-visit tour's "seen" state (per teacher).
  userId,
}) {
  const toast = useToast();
  const t = useT("pdfExportModal", lang);

  // Sticky style from localStorage. Default to classic if first run.
  const [style, setStyle] = useState(() => {
    if (typeof window === "undefined") return DEFAULT_STYLE;
    const saved = window.localStorage?.getItem(STORAGE_KEY);
    if (saved && STYLES[saved]) return saved;
    return DEFAULT_STYLE;
  });
  // PR 32: sticky palette choice
  const [paletteId, setPaletteId] = useState(() => {
    if (typeof window === "undefined") return DEFAULT_PALETTE_ID;
    const saved = window.localStorage?.getItem(PALETTE_STORAGE_KEY);
    if (saved && PALETTES.find((p) => p.id === saved)) return saved;
    return DEFAULT_PALETTE_ID;
  });
  const [variant, setVariant] = useState(
    initialVariant === "answers" ? "answer_key" : "exam"
  );
  const [previewURL, setPreviewURL] = useState(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewError, setPreviewError] = useState(false);
  const [downloading, setDownloading] = useState(false);
  // PR 46: carrusel del style picker. Muestra hasta VISIBLE_STYLES a la
  // vez, flechas L/R para navegar cuando hay más. Empieza centrado en el
  // style seleccionado para que el user vea inmediatamente cuál tiene
  // elegido.
  const [styleScrollIndex, setStyleScrollIndex] = useState(0);

  // Keep previous URL so we can revoke it when we generate a new one
  const previousURL = useRef(null);

  // Persist style choice on change
  useEffect(() => {
    if (typeof window !== "undefined") {
      window.localStorage?.setItem(STORAGE_KEY, style);
    }
  }, [style]);

  // PR 46: cuando cambia el style seleccionado (manualmente o desde
  // localStorage en mount), asegurarse de que sea visible en el
  // carrusel. Si está fuera del slice visible, scrollear para que
  // entre.
  useEffect(() => {
    const idx = styleOptions.findIndex(s => s.id === style);
    if (idx === -1) return;
    if (idx < styleScrollIndex) {
      setStyleScrollIndex(idx);
    } else if (idx >= styleScrollIndex + VISIBLE_STYLES) {
      setStyleScrollIndex(idx - VISIBLE_STYLES + 1);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [style]);

  // PR 32: persist palette choice on change
  useEffect(() => {
    if (typeof window !== "undefined") {
      window.localStorage?.setItem(PALETTE_STORAGE_KEY, paletteId);
    }
  }, [paletteId]);

  // Regenerate preview whenever style, variant, or palette changes
  useEffect(() => {
    let cancelled = false;
    setPreviewLoading(true);
    setPreviewError(false);

    (async () => {
      try {
        const url = await generatePreviewBlobURL(deck, classObj, {
          style, variant, lang, paletteId,
        });
        if (cancelled) {
          URL.revokeObjectURL(url);
          return;
        }
        // Revoke previous URL before swapping (avoids browser memory leak)
        if (previousURL.current) {
          URL.revokeObjectURL(previousURL.current);
        }
        previousURL.current = url;
        setPreviewURL(url);
      } catch (err) {
        console.error("[pdf preview] failed:", err);
        if (!cancelled) setPreviewError(true);
      } finally {
        if (!cancelled) setPreviewLoading(false);
      }
    })();

    return () => { cancelled = true; };
  }, [style, variant, deck, classObj, lang, paletteId]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (previousURL.current) {
        URL.revokeObjectURL(previousURL.current);
        previousURL.current = null;
      }
    };
  }, []);

  const handleDownload = async () => {
    if (downloading) return;
    setDownloading(true);
    try {
      // Use the existing dispatcher — it triggers doc.save() which fires
      // the browser download.
      const { exportPDF } = await import("../lib/pdf-export");
      await exportPDF(deck, classObj, { style, variant, lang, paletteId });
      onClose?.();
    } catch (err) {
      console.error("[pdf download] failed:", err);
      toast.error("PDF download failed. Try again.", { reportError: err, context: { source: "PDFExportModal.download" } });
    } finally {
      setDownloading(false);
    }
  };

  const styleOptions = [
    { id: "classic", name: t.classicName, desc: t.classicDesc, Thumb: STYLE_THUMBS.classic },
    { id: "modern", name: t.modernName, desc: t.modernDesc, Thumb: STYLE_THUMBS.modern },
    { id: "editorial", name: t.editorialName, desc: t.editorialDesc, Thumb: STYLE_THUMBS.editorial },
    { id: "framed", name: t.framedName, desc: t.framedDesc, Thumb: STYLE_THUMBS.framed },
  ];

  return (
    <Modal
      open
      onClose={onClose}
      ariaLabelledBy="pdfexport-title"
      backdropStyle={{
        position: "fixed", inset: 0,
        background: "rgba(0,0,0,0.45)",
        display: "flex", alignItems: "center", justifyContent: "center",
        zIndex: 100,
        padding: 20,
      }}
      dialogStyle={{
        background: C.bg,
        borderRadius: 14,
        maxWidth: 760, width: "100%",
        maxHeight: "92vh",
        display: "flex", flexDirection: "column",
        boxShadow: SH.lg,
        overflow: "hidden",
      }}
    >
        {/* Header */}
        <div style={{ padding: "20px 24px 12px", borderBottom: `1px solid ${C.border}` }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
            <div>
              <h3 id="pdfexport-title" style={{ margin: 0, fontSize: 18, fontWeight: 700, color: C.text }}>{t.title}</h3>
              <p style={{ margin: "4px 0 0", fontSize: 13, color: C.textSecondary }}>{t.subtitle}</p>
            </div>
            <button
              onClick={onClose}
              aria-label={t.close}
              style={{
                background: "transparent", border: "none", cursor: "pointer",
                fontSize: 20, color: C.textMuted, padding: 4,
                lineHeight: 1,
              }}
            >{"\u00D7"}</button>
          </div>
        </div>

        {/* Body — scrollable */}
        <div style={{ overflowY: "auto", padding: "16px 24px", flex: 1 }}>
          {/* PR 46.1: variant selector — los 3 botones en una sola fila.
              Exam y Exam+scan toman el espacio principal (flex: 1 cada
              uno), AK queda a la derecha con tamaño natural — chiquito
              pero al mismo nivel. */}
          <div data-tour="pdf-variant" style={{ marginBottom: 18 }}>
            <label style={{ display: "block", fontSize: 12, fontWeight: 600, color: C.textSecondary, marginBottom: 6, textTransform: "uppercase", letterSpacing: 0.4 }}>
              {t.variantLabel}
            </label>
            <div style={{ display: "flex", gap: 8, alignItems: "stretch" }}>
              {[
                { id: "exam", label: t.variantExam },
                { id: "exam_with_scan", label: t.variantExamWithScan },
              ].map(v => (
                <button
                  key={v.id}
                  onClick={() => setVariant(v.id)}
                  style={{
                    flex: 1,
                    padding: "10px 12px",
                    borderRadius: 9,
                    border: `1.5px solid ${variant === v.id ? C.accent : C.border}`,
                    background: variant === v.id ? C.accentSoft : C.bg,
                    color: variant === v.id ? C.accent : C.text,
                    fontWeight: 600,
                    fontSize: 12.5,
                    cursor: "pointer",
                    fontFamily: "inherit",
                    transition: "border-color 0.15s, background 0.15s",
                    whiteSpace: "nowrap",
                  }}
                >{v.label}</button>
              ))}
              <button
                onClick={() => setVariant("answer_key")}
                title={t.variantKeyTooltip}
                style={{
                  padding: "10px 14px",
                  borderRadius: 9,
                  border: `1.5px solid ${variant === "answer_key" ? C.accent : C.border}`,
                  background: variant === "answer_key" ? C.accentSoft : C.bg,
                  color: variant === "answer_key" ? C.accent : C.textMuted,
                  fontWeight: 600,
                  fontSize: 12.5,
                  cursor: "pointer",
                  fontFamily: "inherit",
                  letterSpacing: 0.3,
                  flexShrink: 0,
                }}
              >{t.variantKey}</button>
            </div>
          </div>

          {/* PR 46: Style picker — carrusel con flechas L/R. Muestra
              hasta VISIBLE_STYLES (3) opciones a la vez. Las flechas se
              deshabilitan en los extremos. Si total <= VISIBLE_STYLES,
              las flechas no se renderizan (siempre vemos todo). */}
          <div data-tour="pdf-style" style={{ marginBottom: 18 }}>
            <label style={{ display: "block", fontSize: 12, fontWeight: 600, color: C.textSecondary, marginBottom: 6, textTransform: "uppercase", letterSpacing: 0.4 }}>
              {t.styleLabel}
            </label>
            {(() => {
              const total = styleOptions.length;
              const showArrows = total > VISIBLE_STYLES;
              const maxIndex = Math.max(0, total - VISIBLE_STYLES);
              const safeIndex = Math.min(styleScrollIndex, maxIndex);
              const visibleSlice = styleOptions.slice(safeIndex, safeIndex + VISIBLE_STYLES);
              const canPrev = safeIndex > 0;
              const canNext = safeIndex < maxIndex;

              const arrowBtn = (direction, enabled, onClick) => (
                <button
                  onClick={onClick}
                  disabled={!enabled}
                  aria-label={direction === "prev" ? "Previous styles" : "Next styles"}
                  style={{
                    flexShrink: 0,
                    width: 32,
                    height: 32,
                    alignSelf: "center",
                    borderRadius: 8,
                    border: `1px solid ${C.border}`,
                    background: enabled ? C.bg : "transparent",
                    color: enabled ? C.text : C.textMuted,
                    cursor: enabled ? "pointer" : "default",
                    opacity: enabled ? 1 : 0.35,
                    fontFamily: "inherit",
                    fontSize: 14,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    transition: "opacity 0.15s, background 0.15s",
                  }}
                >{direction === "prev" ? "‹" : "›"}</button>
              );

              return (
                <div style={{ display: "flex", gap: 8, alignItems: "stretch" }}>
                  {showArrows && arrowBtn("prev", canPrev, () => setStyleScrollIndex(i => Math.max(0, i - 1)))}
                  <div style={{
                    flex: 1,
                    display: "grid",
                    gridTemplateColumns: `repeat(${VISIBLE_STYLES}, 1fr)`,
                    gap: 8,
                  }}>
                    {visibleSlice.map(s => (
                      <button
                        key={s.id}
                        onClick={() => setStyle(s.id)}
                        style={{
                          background: C.bg,
                          border: `2px solid ${style === s.id ? C.accent : C.border}`,
                          borderRadius: 10,
                          padding: 8,
                          cursor: "pointer",
                          display: "flex", flexDirection: "column", alignItems: "center", gap: 6,
                          fontFamily: "inherit",
                          transition: "border-color 0.15s",
                        }}
                      >
                        <div style={{ width: "100%", borderRadius: 4, overflow: "hidden", background: "#fff" }}>
                          <s.Thumb />
                        </div>
                        <div style={{ textAlign: "center" }}>
                          <div style={{ fontSize: 13, fontWeight: 600, color: C.text }}>{s.name}</div>
                          <div style={{ fontSize: 11, color: C.textMuted, marginTop: 1 }}>{s.desc}</div>
                        </div>
                      </button>
                    ))}
                  </div>
                  {showArrows && arrowBtn("next", canNext, () => setStyleScrollIndex(i => Math.min(maxIndex, i + 1)))}
                </div>
              );
            })()}
          </div>

          {/* PR 32: Palette picker — color swatches as chips */}
          <div style={{ marginBottom: 18 }}>
            <label style={{ display: "block", fontSize: 12, fontWeight: 600, color: C.textSecondary, marginBottom: 6, textTransform: "uppercase", letterSpacing: 0.4 }}>
              {t.paletteLabel}
            </label>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
              {PALETTES.map(p => {
                const isSelected = paletteId === p.id;
                const qC = p.previewQuestion;
                const aC = p.previewAnswer;
                const paletteName = lang === "es" ? p.nameEs : (lang === "ko" ? p.nameKo : p.nameEn);
                return (
                  <button
                    key={p.id}
                    onClick={() => setPaletteId(p.id)}
                    title={paletteName}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: 6,
                      padding: "6px 10px 6px 6px",
                      borderRadius: 999,
                      border: `2px solid ${isSelected ? C.accent : C.border}`,
                      background: isSelected ? C.accentSoft : C.bg,
                      cursor: "pointer",
                      fontFamily: "inherit",
                      fontSize: 12,
                      fontWeight: 600,
                      color: isSelected ? C.accent : C.textSecondary,
                      transition: "border-color 0.15s",
                    }}
                  >
                    {/* Two-color swatch — question color + answer color side by side */}
                    <div style={{ display: "flex", borderRadius: 999, overflow: "hidden", boxShadow: "inset 0 0 0 1px rgba(0,0,0,0.06)" }}>
                      <div style={{
                        width: 12, height: 12,
                        background: `rgb(${qC[0]},${qC[1]},${qC[2]})`,
                      }} />
                      <div style={{
                        width: 12, height: 12,
                        background: `rgb(${aC[0]},${aC[1]},${aC[2]})`,
                      }} />
                    </div>
                    <span>{paletteName}</span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Preview */}
          <div>
            <label style={{ display: "block", fontSize: 12, fontWeight: 600, color: C.textSecondary, marginBottom: 6, textTransform: "uppercase", letterSpacing: 0.4 }}>
              {t.previewLabel}
            </label>
            <div style={{
              position: "relative",
              border: `1px solid ${C.border}`,
              borderRadius: 8,
              background: C.bgSoft,
              height: 360,
              overflow: "hidden",
            }}>
              {previewURL && !previewError && (
                <iframe
                  src={previewURL}
                  title="PDF preview"
                  style={{ width: "100%", height: "100%", border: "none", background: "#fff" }}
                />
              )}
              {previewLoading && (
                <div style={{
                  position: "absolute", inset: 0,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontSize: 13, color: C.textMuted,
                  background: previewURL ? C.bgSoft : "transparent",
                }}>
                  {t.previewLoading}
                </div>
              )}
              {previewError && !previewLoading && (
                <div style={{
                  position: "absolute", inset: 0,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontSize: 13, color: C.textMuted, padding: 20, textAlign: "center",
                }}>
                  {t.previewFailed}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Footer actions */}
        <div style={{
          padding: "14px 24px",
          borderTop: `1px solid ${C.border}`,
          display: "flex", justifyContent: "flex-end", gap: 10,
          background: C.bgSoft,
        }}>
          <Button variant="secondary" size="sm" onClick={onClose}>{t.cancel}</Button>
          <Button variant="primary" size="sm" loading={downloading} onClick={handleDownload} data-tour="pdf-download">{t.download}</Button>
        </div>

        {/* First-visit guided tour — pick a style → download. */}
        <CleoTour tourId="pdfExport" lang={lang} userId={userId} enabled />
    </Modal>
  );
}
